# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\shihui\ericproject\bookstore\mainfram.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_mainfram(object):
    def setupUi(self, mainfram):
        mainfram.setObjectName(_fromUtf8("mainfram"))
        mainfram.resize(670, 486)
        self.centralWidget = QtGui.QWidget(mainfram)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.taborder = QtGui.QTabWidget(self.centralWidget)
        self.taborder.setGeometry(QtCore.QRect(0, 0, 671, 461))
        self.taborder.setObjectName(_fromUtf8("taborder"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.search = QtGui.QPushButton(self.tab)
        self.search.setGeometry(QtCore.QRect(460, 40, 75, 23))
        self.search.setObjectName(_fromUtf8("search"))
        self.dataview = QtGui.QTableView(self.tab)
        self.dataview.setGeometry(QtCore.QRect(0, 130, 671, 301))
        self.dataview.setAutoFillBackground(True)
        self.dataview.setObjectName(_fromUtf8("dataview"))
        self.itemcommo = QtGui.QComboBox(self.tab)
        self.itemcommo.setEnabled(True)
        self.itemcommo.setGeometry(QtCore.QRect(320, 40, 101, 27))
        self.itemcommo.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.itemcommo.setAcceptDrops(True)
        self.itemcommo.setStatusTip(_fromUtf8(""))
        self.itemcommo.setAccessibleName(_fromUtf8(""))
        self.itemcommo.setAccessibleDescription(_fromUtf8(""))
        self.itemcommo.setStyleSheet(_fromUtf8(""))
        self.itemcommo.setEditable(False)
        self.itemcommo.setMaxCount(5)
        self.itemcommo.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContentsOnFirstShow)
        self.itemcommo.setDuplicatesEnabled(False)
        self.itemcommo.setModelColumn(0)
        self.itemcommo.setObjectName(_fromUtf8("itemcommo"))
        self.searchcontent = QtGui.QLineEdit(self.tab)
        self.searchcontent.setGeometry(QtCore.QRect(110, 40, 151, 27))
        self.searchcontent.setObjectName(_fromUtf8("searchcontent"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(20, 40, 81, 17))
        self.label.setObjectName(_fromUtf8("label"))
        self.datacontent = QtGui.QTableWidget(self.tab)
        self.datacontent.setGeometry(QtCore.QRect(0, 130, 671, 301))
        self.datacontent.setObjectName(_fromUtf8("datacontent"))
        self.datacontent.setColumnCount(0)
        self.datacontent.setRowCount(0)
        self.showallbook = QtGui.QPushButton(self.tab)
        self.showallbook.setGeometry(QtCore.QRect(550, 40, 98, 27))
        self.showallbook.setObjectName(_fromUtf8("showallbook"))
        self.taborder.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.label_2 = QtGui.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(70, 60, 81, 17))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.searchordercontent = QtGui.QLineEdit(self.tab_2)
        self.searchordercontent.setGeometry(QtCore.QRect(160, 60, 131, 27))
        self.searchordercontent.setObjectName(_fromUtf8("searchordercontent"))
        self.ordercommobox = QtGui.QComboBox(self.tab_2)
        self.ordercommobox.setGeometry(QtCore.QRect(330, 60, 111, 27))
        self.ordercommobox.setObjectName(_fromUtf8("ordercommobox"))
        self.ordersearch = QtGui.QPushButton(self.tab_2)
        self.ordersearch.setGeometry(QtCore.QRect(480, 60, 98, 27))
        self.ordersearch.setObjectName(_fromUtf8("ordersearch"))
        self.orderdatacontent = QtGui.QTableWidget(self.tab_2)
        self.orderdatacontent.setGeometry(QtCore.QRect(0, 160, 671, 271))
        self.orderdatacontent.setObjectName(_fromUtf8("orderdatacontent"))
        self.orderdatacontent.setColumnCount(0)
        self.orderdatacontent.setRowCount(0)
        self.showallorder = QtGui.QPushButton(self.tab_2)
        self.showallorder.setGeometry(QtCore.QRect(480, 100, 98, 27))
        self.showallorder.setObjectName(_fromUtf8("showallorder"))
        self.taborder.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.label_3 = QtGui.QLabel(self.tab_3)
        self.label_3.setGeometry(QtCore.QRect(110, 70, 81, 17))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.buysearchcontent = QtGui.QLineEdit(self.tab_3)
        self.buysearchcontent.setGeometry(QtCore.QRect(200, 70, 131, 27))
        self.buysearchcontent.setObjectName(_fromUtf8("buysearchcontent"))
        self.buycommobox = QtGui.QComboBox(self.tab_3)
        self.buycommobox.setGeometry(QtCore.QRect(360, 70, 111, 27))
        self.buycommobox.setObjectName(_fromUtf8("buycommobox"))
        self.buy_time_search = QtGui.QPushButton(self.tab_3)
        self.buy_time_search.setGeometry(QtCore.QRect(500, 70, 98, 27))
        self.buy_time_search.setObjectName(_fromUtf8("buy_time_search"))
        self.showallbuy = QtGui.QPushButton(self.tab_3)
        self.showallbuy.setGeometry(QtCore.QRect(500, 120, 98, 27))
        self.showallbuy.setObjectName(_fromUtf8("showallbuy"))
        self.buydatacontent = QtGui.QTableWidget(self.tab_3)
        self.buydatacontent.setGeometry(QtCore.QRect(0, 160, 671, 271))
        self.buydatacontent.setObjectName(_fromUtf8("buydatacontent"))
        self.buydatacontent.setColumnCount(0)
        self.buydatacontent.setRowCount(0)
        self.taborder.addTab(self.tab_3, _fromUtf8(""))
        mainfram.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(mainfram)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 670, 28))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menu = QtGui.QMenu(self.menuBar)
        self.menu.setObjectName(_fromUtf8("menu"))
        self.menu_2 = QtGui.QMenu(self.menuBar)
        self.menu_2.setObjectName(_fromUtf8("menu_2"))
        mainfram.setMenuBar(self.menuBar)
        self.action = QtGui.QAction(mainfram)
        self.action.setObjectName(_fromUtf8("action"))
        self.menu.addAction(self.action)
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())

        self.retranslateUi(mainfram)
        self.taborder.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mainfram)

    def retranslateUi(self, mainfram):
        mainfram.setWindowTitle(_translate("mainfram", "MainWindow", None))
        self.search.setText(_translate("mainfram", "查询", None))
        self.label.setText(_translate("mainfram", "请输入内容", None))
        self.showallbook.setText(_translate("mainfram", "查看全部书目", None))
        self.taborder.setTabText(self.taborder.indexOf(self.tab), _translate("mainfram", "书目检索", None))
        self.label_2.setText(_translate("mainfram", "请输入内容", None))
        self.ordersearch.setText(_translate("mainfram", "查询", None))
        self.showallorder.setText(_translate("mainfram", "显示全部订单", None))
        self.taborder.setTabText(self.taborder.indexOf(self.tab_2), _translate("mainfram", "订单检索", None))
        self.label_3.setText(_translate("mainfram", "请输入内容", None))
        self.buy_time_search.setText(_translate("mainfram", "查询", None))
        self.showallbuy.setText(_translate("mainfram", "显示全部", None))
        self.taborder.setTabText(self.taborder.indexOf(self.tab_3), _translate("mainfram", "购买次数检索", None))
        self.menu.setTitle(_translate("mainfram", "文件", None))
        self.menu_2.setTitle(_translate("mainfram", "关于", None))
        self.action.setText(_translate("mainfram", "退出", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    mainfram = QtGui.QMainWindow()
    ui = Ui_mainfram()
    ui.setupUi(mainfram)
    mainfram.show()
    sys.exit(app.exec_())

